services:
  - type: web
    plan: free
    name: URL-Shortner-Bot-V2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/Adheei/URL-Shortner-Bot-V2.git      
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: AUTH_CHANNEL
        sync: false
      - key: DATABASE_URL 
        sync: false 
      - key: ADMINS
        sync: false    
      - key: BOT_OWNER
        sync: false
      - key: GPLINKS_API
        sync: false

    autoDeploy: false 
